/*
 * This is a utility that attempt to measure stack usage
 * This relies on undefined behavior and works by assuming a specific
 * stack behavior by the CPU; for one, that the stack grows downward
 * in memory
 * It works by filling in an array on the stack with a known pattern
 * then you run the routines you want to measure the stack usage, and
 * then it looks at that array to see what has been overwritten
 *
 * The usage is:
 *   init_stack();
 *   run_routines_under_test();
 *   unsigned stack_usage = measure_stack();
 *
 * This works on my CPU/compiler; it may need to be tweaked for yours
 */

#include "stack.h"

#define N 10000 /* The size of the test array */
                /* None of the routines we test will overwrite this much */

void init_stack(void) {
    /* Fill in the array with the known pattern (which is unlikely */
    /* to be generated by the routines under test */
    unsigned char array[N];
    for (int i=0; i<N; i++) array[i] = 'x';
}

unsigned measure_stack(void) {
    /* Define the same array (in the same place on the stack) and */
    /* scan for where the known pattern was overwritten */
    unsigned char array[N];
    int i;
    for (i=0; i<N; i++) if (array[i] != 'x') break;

    return N-i;
}
